[pytest]
filterwarnings =
    ignore::DeprecationWarning
markers =
    slow: marks tests as slow (deselected unless --runslow is given)
    vtk: marks tests as requiring vtk and vtk test data
    vtu: marks tests as requiring COMSOL vtu test data
